import {validateInteractionNavigation} from './interaction_navigation.mjs';
import {CELL as C,wallBit,FACE} from '../jCRPG-engine/js/world/format.js';
import {validateContent,validateAnchor,compareId} from '../jCRPG-engine/js/interactions/format.js';
import {solvePuzzle} from '../jCRPG-engine/js/interactions/puzzles.js';
import {CULTURES,LAYERS,START_TOWN,START_SHRINE,START_MISSION} from './mission_templates.mjs';
const dist=(a,b)=>Math.hypot(...[0,2].map(i=>{const n=Math.abs(a[i]-b[i]);return Math.min(n,1600-n);}));
const sourceKind='web-authored-generated';
export function compileInteractions({data,world,chunks,structures,portals,emit}){
 const content={actors:[],dialogues:[],missions:[],puzzles:[],shrines:[],containers:[],itemTypes:[],initialInventory:data.objectInstances,cultures:[],settlements:[],routes:[],goals:[],generators:[]};
 const chunk=(x,z)=>chunks[Math.floor(z/32)*50+Math.floor(x/32)];
 const occupied=new Set(),navigation=new Map();
 for(const c of chunks){c.interactions=[];for(const row of c.cells){const s=c.structures[row[4]],realm=s.kind==='cave'?'cave':'surface',key=`${realm}:${c.x*32+row[0]}:${row[1]}:${c.z*32+row[2]}`;navigation.set(key,(navigation.get(key)??0)|row[3]);}}
 // Match the compiler's flattened, two-unit terrain interpolation exactly.
 const flatHeights=new Map(),groundCells=new Map();
 for(const st of structures)for(let z=st.origin[2]-1;z<=st.origin[2]+st.size[2];z++)for(let x=st.origin[0]-1;x<=st.origin[0]+st.size[0];x++)flatHeights.set(`${(x+1600)%1600}:${(z+1600)%1600}`,st.origin[1]);
 for(const c of chunks)for(const row of c.cells)if(c.structures[row[4]].kind!=='cave'){
  const key=(c.x*32+row[0])+':'+(c.z*32+row[2]),old=groundCells.get(key);if(!old||row[1]<old.y)groundCells.set(key,{y:row[1],flags:row[3]});else if(row[1]===old.y)old.flags|=row[3];
 }
 function surfaceFloor(x,z){const cell=groundCells.get(Math.floor(x)+':'+Math.floor(z));if(cell?.flags&C.FLOOR)return cell.y;const gx=Math.floor(x/2)*2,gz=Math.floor(z/2)*2,u=(x-gx)/2,v=(z-gz)/2,h=(x,z)=>Math.fround(flatHeights.get(`${(x+1600)%1600}:${(z+1600)%1600}`)??world.heightAt(x,z));return u>=v?h(gx,gz)*(1-u)+h(gx+2,gz)*(u-v)+h(gx+2,gz+2)*v:h(gx,gz)*(1-v)+h(gx,gz+2)*(v-u)+h(gx+2,gz+2)*u;}
 const nav=(x,y,z,realm='surface')=>navigation.get(`${realm}:${x}:${y}:${z}`)??0;
 function free(p,realm){const [x,y,z]=p.map(Math.floor),flags=nav(x,y,z,realm);return !(flags&(C.BLOCK|C.STAIRS|C.N|C.E|C.S|C.W))&&(realm!=='cave'||!!(flags&C.FLOOR));}
 function safeNear(p,realm='surface',radius=20){
  for(let r=0;r<=radius;r++)for(let z=-r;z<=r;z++)for(let x=-r;x<=r;x++){
   if(r&&Math.max(Math.abs(x),Math.abs(z))!==r)continue;
   const q=[Math.floor(p[0])+x+.5,p[1],Math.floor(p[2])+z+.5];if(q[0]<1||q[2]<1||q[0]>=1599||q[2]>=1599)continue;
   if(realm==='surface')q[1]=surfaceFloor(q[0],q[2]);
   const key=realm+':'+q.join(':');if(occupied.has(key)||!free(q,realm))continue;
   // Surface actors outside interiors. A nearby ground patch retains legacy floor.
   if(realm==='surface'&&(nav(Math.floor(q[0]),Math.floor(q[1]),Math.floor(q[2]))&C.INTERIOR))continue;
   if([...occupied].some(k=>{const a=k.split(':');return a[0]===realm&&Math.hypot(+a[1]-q[0],+a[3]-q[2])<2.4;}))continue;
   occupied.add(key);return q;
  }throw Error('No safe interaction placement near '+p);
 }
 function anchor(kind,targetId,position,{realm='surface',prompt,componentId,fact,priority,asset,...extra}={}){
  const a={id:'interaction:'+kind+':'+(componentId??targetId),kind,targetId,position,realm,range:2.1,priority:priority??({actor:70,shrine:50,puzzle:90,container:60,evidence:85}[kind]),prompt:prompt??'Interact',requiresLineOfSight:true,...(componentId?{componentId}:{}),...(fact?{fact}:{}),...extra};validateAnchor(a);chunk(position[0],position[2]).interactions.push(a);
  if(asset)emit(asset,...position,0,[1,1,1],{realm,interactionId:a.id,stateTargetId:targetId,componentId,actorId:kind==='actor'?targetId:undefined,settlementId:extra.settlementId});
  content.goals.push({id:'goal:'+a.id,kind,targetId,position,realm,...(fact?{fact}:{}),sourceKind});return a;
 }
 const districtById=new Map(data.districts.map(d=>[d.id,d]));
 // Restore owner links omitted by the old big-block labyrinth adapter.
 for(const s of structures)if(s.kind==='SimpleDungeonPart')s.ownerMemberId=districtById.get(s.districtId)?.fixedInfrastructure[0]?.ownerMemberId??null;
 const byCulture=Object.fromEntries(CULTURES.map(c=>[c.legacy,c.id]));
 for(const town of data.towns){const ds=town.districtIds.map(id=>districtById.get(id)),presence={};for(const d of ds){const id=byCulture[d.ownerType];presence[id]??={districts:0,inhabitants:0};presence[id].districts++;presence[id].inhabitants+=d.savedInhabitantNumber;}
  const dominant=Object.keys(presence).sort((a,b)=>presence[b].districts-presence[a].districts||compareId(a,b))[0],s=structures.find(s=>s.townId===town.id);
  content.settlements.push({id:town.id,name:town.name,position:[town.center[0],s?.origin[1]??world.heightAt(...town.center),town.center[1]],realm:'surface',cultureIds:Object.keys(presence).sort(),dominantCultureId:dominant,presence,settlementTier:'minor',districtIds:town.districtIds,sourceKind:'legacy-derived'});
 }
 // Authored cave settlements use real component entrances and their walkable floors.
 const caveCandidates=portals.filter(p=>p.kind==='cave'&&p.componentSize>=150).sort((a,b)=>b.componentSize-a.componentSize||compareId(a.id,b.id));
 const home=portals.find(p=>p.id==='cave:760:840:0');if(!home)throw Error('Deep Ledger cave missing');
 const selected=[home];while(selected.length<9){const candidate=caveCandidates.filter(p=>!selected.includes(p)).sort((a,b)=>Math.min(...selected.map(p=>dist(b.from,p.from)))-Math.min(...selected.map(p=>dist(a.from,p.from)))||compareId(a.id,b.id))[0];if(!candidate)throw Error('Not enough Kobold cave sites');selected.push(candidate);}
 selected.forEach((p,i)=>content.settlements.push({id:i?'town:kobold:crew-'+i:'town:kobold:deep-ledger',name:i?'Listening Crew '+i:'Deep Ledger',position:[...p.to],entrancePosition:p.from,portalId:p.id,realm:'cave',cultureIds:['kobold'],dominantCultureId:'kobold',presence:{kobold:{districts:1,inhabitants:0}},districtIds:[],settlementTier:'minor',sourceKind}));
 const settlements=new Map(content.settlements.map(t=>[t.id,t]));
 for(const c of CULTURES){const capital=settlements.get(c.capital);if(!capital)throw Error('Fixed capital missing: '+c.capital);capital.settlementTier='capital';capital.capitalCultureId=c.id;
  const candidates=content.settlements.filter(t=>t.id!==capital.id&&t.id!==START_TOWN&&t.dominantCultureId===c.id&&t.settlementTier==='minor');
  const secondaries=[];while(secondaries.length<4){candidates.sort((a,b)=>{const reach=t=>Math.min(...[capital,...secondaries].map(s=>dist(t.position,s.position)));return reach(b)-reach(a)||b.presence[c.id].inhabitants-a.presence[c.id].inhabitants||compareId(a.id,b.id);});const town=candidates.shift();if(!town)throw Error('Insufficient major towns for '+c.id);town.settlementTier='secondary-capital';town.parentCapitalTownId=capital.id;town.layer=LAYERS[secondaries.length];secondaries.push(town);}
  for(const t of candidates){const nearest=[...secondaries].sort((a,b)=>dist(t.position,a.position)-dist(t.position,b.position)||compareId(a.id,b.id))[0];t.parentCapitalTownId=capital.id;t.parentSecondaryCapitalTownId=nearest.id;}
  // A regional task always has an actual minor site, not a duplicate major node.
  for(const major of secondaries){if(!candidates.some(t=>t.parentSecondaryCapitalTownId===major.id)){const donor=candidates.filter(t=>candidates.filter(x=>x.parentSecondaryCapitalTownId===t.parentSecondaryCapitalTownId).length>1).sort((a,b)=>dist(a.position,major.position)-dist(b.position,major.position)||compareId(a.id,b.id))[0];if(!donor)throw Error('No minor settlement for '+major.id);donor.parentSecondaryCapitalTownId=major.id;}}
  content.cultures.push({id:c.id,displayName:c.name,legacyEntityTypes:[c.legacy],pairId:c.pair,expression:c.expression,capitalTownId:capital.id,secondaryCapitalTownIds:secondaries.map(t=>t.id),layerOrder:[...LAYERS,'bliss'],sourceKind});
  for(const t of [capital,...secondaries,...candidates])t.capitalRankEvidence={culturalDistricts:t.presence[c.id]?.districts??0,culturalInhabitants:t.presence[c.id]?.inhabitants??0,totalDistricts:t.districtIds.length,selection:t===capital?'authoritative-seed0':t.settlementTier==='secondary-capital'?'geographic-coverage':'nearest-region'};
 }
 function actor(id,name,role,town,position,text,legacy=null,cultureId=null){const a={id,name,role,townId:town.id,cultureId:cultureId??town.dominantCultureId,position:safeNear(position??town.position,town.realm),realm:town.realm,legacy,sourceKind,nameSource:sourceKind,anchorKind:legacy?'owned-structure':'generated-guide',missionIds:[],dialogueId:'dialogue:'+id,integratedText:'The regional circuits now answer together. We keep the measured record open and renew our obligations through ordinary care.',stableText:'The local circuit is stable. Its households and shared services now receive their measured current. We still need to keep the wider network answerable to these observations.'};content.actors.push(a);content.dialogues.push({id:a.dialogueId,start:'greeting',nodes:{greeting:{text,knowledge:'testimony',choices:[{text:'Until next time.'}]}}});anchor('actor',id,a.position,{realm:a.realm,prompt:'Talk to '+name,asset:'actor_'+a.cultureId,settlementId:town.id});return a;}
 const dialogue=a=>content.dialogues.find(d=>d.id===a.dialogueId).nodes.greeting;
 function mission(id,title,summary,giver,objectives,{requires=[],onComplete=[],layer='body',cultureId=giver.cultureId}={}){const m={id,title,summary,giverActorId:giver.id,turnInActorId:giver.id,objectives,requires,onComplete,layer,cultureId,sourceKind};content.missions.push(m);giver.missionIds.push(id);const n=dialogue(giver);n.choices.unshift({text:'Accept: '+title,when:{missionState:[id,'available']},actions:[{op:'accept',id}]},{text:'Report: '+title,when:{missionState:[id,'ready-to-turn-in']},actions:[{op:'turnIn',id}]},{text:'Review: '+title,when:{missionState:[id,'active']},next:'hint:'+id});content.dialogues.find(d=>d.id===giver.dialogueId).nodes['hint:'+id]={text:summary+' '+objectives.map(o=>o.text).join(' '),knowledge:'inference',choices:[{text:'Back',next:'greeting'}]};return m;}
 const objective=(id,kind,targetIds,text)=>({id,kind,targetIds,text,required:targetIds.length,backfill:true});
 function evidence(id,position,town,text){const p=safeNear(position,town.realm);anchor('evidence',id,p,{realm:town.realm,prompt:'Inspect reading',fact:'Fact: '+text,asset:'conductor'});return id;}
 function puzzle(id,town,position,{demands=[1,2,3],labels=['One','Two','Three'],family='balanced',positions=null,onComplete=[],fact='The three demands are independent measured loads.'}={}){
  const components=labels.map((_,i)=>id+':conductor:'+i),sequence=[components[1],components[0],components[2]],p={id,townId:town.id,family,demands,labels,capacity:demands.reduce((a,b)=>a+b,0),componentIds:components,sequence,resettable:true,wrongInput:'reset',onComplete,fact,sourceKind};content.puzzles.push(p);
  components.forEach((componentId,i)=>{const pos=positions?.[i]??safeNear([position[0]+i*3,position[1],position[2]],town.realm);anchor('puzzle',id,pos,{realm:town.realm,componentId,prompt:`Tune ${labels[i]}`,asset:'conductor'});});
  const reset=safeNear([position[0]-3,position[1],position[2]],town.realm);anchor('puzzle',id,reset,{realm:town.realm,componentId:id+':reset',prompt:'Reset / read circuit',asset:'resetStone',input:'reset'});p.position=positions?.[0]??content.goals.find(g=>g.targetId===id).position;
  p.solution=solvePuzzle(p).inputs;return p;
 }
 // All shrines have one activation identity and a stable undirected relay graph.
 for(const s of structures.filter(s=>s.kind==='RoadShrine')){const position=[s.origin[0]+s.size[0]/2,s.origin[1],s.origin[2]+s.size[2]/2];content.shrines.push({id:s.id,position,neighbors:[],sourceKind});anchor('shrine',s.id,position,{prompt:'Attune shrine',range:3.2});for(const c of chunks)for(const n of c.nodes)if(n.name==='shrine'&&n.userData.jcrpg.structureId===s.id)Object.assign(n.userData.jcrpg,{stateTargetId:s.id,interactionId:'interaction:shrine:'+s.id});}
 const edge=(a,b)=>{if(a.neighbors.some(n=>n.id===b.id))return;const cost=+dist(a.position,b.position).toFixed(4);a.neighbors.push({id:b.id,cost});b.neighbors.push({id:a.id,cost});};
 const connected=[content.shrines[0]],remaining=new Set(content.shrines.slice(1));while(remaining.size){let best=null;for(const a of connected)for(const b of remaining){const d=dist(a.position,b.position);if(!best||d<best.d)best={a,b,d};}edge(best.a,best.b);remaining.delete(best.b);connected.push(best.b);}
 for(const a of content.shrines)for(const b of [...content.shrines].filter(b=>b!==a).sort((b,c)=>dist(a.position,b.position)-dist(a.position,c.position)||compareId(b.id,c.id)).slice(0,2))edge(a,b);
 const shrineMap=new Map(content.shrines.map(s=>[s.id,s]));
 function route(id,start,town){const target=[...content.shrines].sort((a,b)=>dist(a.position,town.entrancePosition??town.position)-dist(b.position,town.entrancePosition??town.position)||compareId(a.id,b.id))[0],cost=new Map([[start,0]]),prev=new Map(),pending=new Set(content.shrines.map(s=>s.id));while(pending.size){const a=[...pending].sort((a,b)=>(cost.get(a)??Infinity)-(cost.get(b)??Infinity)||compareId(a,b))[0];pending.delete(a);if(a===target.id)break;for(const n of shrineMap.get(a).neighbors)if((cost.get(a)??Infinity)+n.cost<(cost.get(n.id)??Infinity)){cost.set(n.id,cost.get(a)+n.cost);prev.set(n.id,a);}}const ids=[target.id];while(ids[0]!==start){const p=prev.get(ids[0]);if(!p)throw Error('Disconnected shrine route');ids.unshift(p);}const r={id,destinationTownId:town.id,destinationName:town.name,shrineIds:ids,sourceKind};content.routes.push(r);return r;}
 const startTown=settlements.get(START_TOWN);
 const boarmanRegion=content.settlements.filter(t=>t.parentCapitalTownId==='town:populationBoarmanTribe#23'&&t.settlementTier==='secondary-capital').sort((a,b)=>dist(a.position,startTown.position)-dist(b.position,startTown.position)||compareId(a.id,b.id))[0];
 startTown.parentCapitalTownId='town:populationBoarmanTribe#23';startTown.parentSecondaryCapitalTownId=boarmanRegion.id;
 const marnLegacy=data.actors.find(a=>a.numericId==='544'),marn=actor(marnLegacy.id,'Marn Even-Tally','Factor of Wammigmig',startTown,[831,40,905],'I can account for every stored unit. I used to call storage priority fairness. Inspect the yard, our homes, and the shared street relay; let the measurements challenge my policy.',marnLegacy,'boarman');
 const pella=actor('actor:wammigmig:pella','Pella Sharekeeper','Resident and keeper of shared needs',startTown,[824,40,910],'Our households need three units, storage two, and the street relay one. Those are measured demands. My claim that households deserve priority is a value you may question.',null,'boarman');
 const orro=actor('actor:wammigmig:orro','Orro Coil-Tender','Itinerant technician',startTown,[787,40,904],'The shrine repeats: homes, storage, street. First inspect each conductor, then cycle its integer setting to the visible demand. When all three match, pulse that same order. Wrong order restarts the rhythm; the reset stone clears the settings.',null,'boarman');
 const wStructures=structures.filter(s=>s.townId===startTown.id);
 const observations=[['storage',[825,40,901],'Storage demand is 2. The conductor is continuous.'],['hut',[830,40,905],'The hut ledger excludes household demand. Total supply is 6.'],['homes',[820,40,907],'Households demand 3 and the public street relay demands 1.']].map(([id,pos,text])=>evidence('evidence:wammigmig:'+id,pos,startTown,text));
 const opening=puzzle('puzzle:wammigmig:distribution',startTown,[819,40,902],{demands:[2,3,1],labels:['Storage','Homes','Street'],onComplete:[{op:'settlement',id:startTown.id,targets:wStructures.map(s=>s.id)},{op:'flag',id:'cave:760:920:0:answered',value:true},{op:'text',text:'Storage, homes and the shared street shine together. The cave to the south answers with a delayed underground pulse.'}]});
 shrineMap.get(START_SHRINE).cue='Observable resonance: Homes → Storage → Street. Wammigmig lies east, about 40 paces away.';
 const handoff=route('route:wammigmig:awshowam',START_SHRINE,settlements.get('town:populationBoarmanTribe#23'));
 dialogue(marn).choices.unshift({text:'Fairness must include households and the shared relay.',when:{puzzle:opening.id},actions:[{op:'commitment',id:'commitment:wammigmig',value:'Publish supply, need and shared obligations together.'}]},{text:'Preserve trade, and make its social costs visible.',when:{puzzle:opening.id},actions:[{op:'commitment',id:'commitment:wammigmig',value:'Keep trade accountable to essential circulation.'}]});
 mission(START_MISSION,'A Fair Share of Light','Awaken the shrine west of spawn. Inspect the three readings in Wammigmig, east of spawn. Match storage 2, homes 3, street 1; then pulse Homes → Storage → Street. Speak to Marn about the result.',marn,[objective('awaken','shrine',[START_SHRINE],'Awaken the nearby relay.'),objective('observe','evidence',observations,'Inspect storage, hut ledger and household readings.'),objective('balance','puzzle',[opening.id],'Balance and attune the three conductors.'),objective('promise','commitment',['commitment:wammigmig'],'Tell Marn which obligation you will keep.')],{onComplete:[{op:'route',id:handoff.id},{op:'flag',id:'letter:garrum',value:true},{op:'text',text:'Marn records your letter of account for Garrum Open-Ledger at Awshowam. Follow the relay frontier westward.'}]});
 // Cultural arcs: local capital repair -> four independent regional tasks -> return synthesis.
 for(const c of CULTURES){const capital=settlements.get(c.capital),arc=content.cultures.find(x=>x.id===c.id),principals=c.people.map(([name,role,text],i)=>actor('actor:'+c.id+':principal:'+i,name,role,capital,[capital.position[0]+i*4,capital.position[1],capital.position[2]],text,null,c.id));
  for(const principal of principals)principal.integratedText=c.synthesis;
  const main=principals[0],local=puzzle('puzzle:'+c.id+':capital',capital,[main.position[0],main.position[1],main.position[2]+5],{demands:c.demands,labels:c.labels,onComplete:[{op:'settlement',id:capital.id,targets:structures.filter(s=>s.townId===capital.id).map(s=>s.id)}]});
  const balance=mission('mission:'+c.id+':balance',c.theme+': A Local Balance',c.people[0][2]+' The three conductors are near the principal. Read each once before changing its setting.',main,[objective('balance','puzzle',[local.id],'Restore the capital’s three local loads.')]);
  const regionalIds=[];
  arc.secondaryCapitalTownIds.forEach((id,i)=>{const town=settlements.get(id),minor=content.settlements.filter(t=>t.parentSecondaryCapitalTownId===id).sort((a,b)=>dist(a.position,town.position)-dist(b.position,town.position)||compareId(a.id,b.id))[0];
   const guide=actor('actor:'+c.id+':regional:'+i,c.name+' '+['Wayfinder','Witness','Measure-Keeper','Mediator'][i],LAYERS[i]+' circuit keeper',town,null,c.layers[i][1]+' Our capital is '+capital.name+'. Its principal will register this work after the local balance. The outlying witness is at '+minor.name+' ('+minor.position[0]+', '+minor.position[2]+').',null,c.id);
   const reading=evidence('evidence:'+c.id+':regional:'+i,minor.position,minor,'Independent reading at '+minor.name+': the circuit carries six units. The allocation is still open to public decision.');
   const paired=CULTURES.find(x=>x.pair===c.pair&&x.id!==c.id),witness=actor('actor:'+c.id+':witness:'+i,paired.name+' visiting witness','Independent '+paired.expression+' perspective',minor,[minor.position[0]+3,minor.position[1],minor.position[2]],paired.people[1][2],null,paired.id);
   const rp=puzzle('puzzle:'+c.id+':regional:'+i,town,[guide.position[0],guide.position[1],guide.position[2]+4],{demands:c.demands,labels:c.labels,family:i===0?'rational':i===1?'resonance':'balanced',onComplete:[{op:'settlement',id:town.id}]});
   const rid='mission:'+c.id+':'+LAYERS[i],commitment='commitment:'+rid;
   dialogue(guide).choices.unshift({text:c.layers[i][1],when:{missionState:[rid,'active']},actions:[{op:'commitment',id:commitment,value:'Keep the '+LAYERS[i]+' obligation; publish revisions honestly.'}]});
   const r=route('route:'+c.id+':'+i,[...content.shrines].sort((a,b)=>dist(a.position,capital.position)-dist(b.position,capital.position))[0].id,town);
   dialogue(main).choices.unshift({text:'Light route to '+town.name,when:{missionState:[balance.id,'completed']},actions:[{op:'route',id:r.id}]});
   mission(rid,c.layers[i][0],c.layers[i][1]+' Inspect '+minor.name+' at '+minor.position[0]+', '+minor.position[2]+', listen to the visiting witness, and repair the circuit beside '+guide.name+'.',guide,[objective('reading','evidence',[reading],'Inspect the independent reading at '+minor.name+'.'),objective('witness','actor',[witness.id],'Listen to the '+paired.name+' witness.'),objective('promise','commitment',[commitment],'Record a testable commitment with the circuit keeper.'),objective('circuit','puzzle',[rp.id],'Restore the regional circuit.')],{requires:[balance.id],layer:LAYERS[i],onComplete:[{op:'settlement',id:minor.id},{op:'settlement',id:town.id}]});regionalIds.push(rid);
  });
  const synthesis='mission:'+c.id+':bliss',breath='commitment:'+c.id+':breath';dialogue(main).choices.unshift({text:c.synthesis,when:{missionState:[synthesis,'active']},actions:[{op:'commitment',id:breath,value:c.synthesis}]});
  mission(synthesis,c.theme,c.synthesis,main,[objective('return','commitment',[breath],'Return to the principal and renew the shared practice.')],{requires:regionalIds,layer:'bliss',onComplete:[capital.id,...arc.secondaryCapitalTownIds].map(id=>({op:'settlement',id,state:'integrated'}))});
 }
 // Labyrinth components come from the actual entrance-connected semantic graph.
 function reachable(s,realm='surface',start=null){const [ox,y,oz]=s.origin,found=[];for(let z=oz;z<oz+s.size[2];z++)for(let x=ox;x<ox+s.size[0];x++){const f=nav(x,y,z,realm);if((f&C.FLOOR)&&!(f&C.BLOCK))found.push([x,y,z]);}if(!found.length)throw Error('Empty maze');const first=start??found.find(([x,,z])=>x===ox||z===oz||x===ox+s.size[0]-1||z===oz+s.size[2]-1)??found[0],queue=[first],seen=new Set([first.join(':')]);for(let k=0;k<queue.length;k++){const [x,y,z]=queue[k],f=nav(x,y,z,realm);for(let face=0;face<4;face++){const n=[x+FACE[face][0],y,z+FACE[face][1]],nf=nav(...n,realm);if(!(nf&C.FLOOR)||(nf&C.BLOCK)||(f&wallBit(face))||(nf&wallBit((face+2)%4)))continue;const key=n.join(':');if(!seen.has(key)){seen.add(key);queue.push(n);}}}return queue.map(p=>[p[0]+.5,p[1],p[2]+.5]);}
 for(const s of structures.filter(s=>s.kind==='SimpleDungeonPart')){
  const town=settlements.get(s.townId),cells=reachable(s),indices=[.12,.45,.8].map(f=>Math.floor((cells.length-1)*f)),positions=indices.map(i=>cells[i]);
  const legacy=data.actors.find(a=>a.numericId===s.ownerMemberId),keeper=actor(legacy.id,'Maze Keeper '+legacy.numericId,'Threshold witness',town,[s.origin[0]-1,s.origin[1],s.origin[2]+1],'Fact: the passages connect and quantities are conserved. Inference: one shortest path is the only useful path. The chorus disputes that inference. Read all three conductors, match their demand, then repeat Two → One → Three. Components are marked in your journal after acceptance.',legacy,'greek');
  const linked=[...content.shrines].sort((a,b)=>dist(a.position,cells[0])-dist(b.position,cells[0])||compareId(a.id,b.id))[0],id='generator:'+s.id;
  const p=puzzle('puzzle:'+id,town,keeper.position,{positions,onComplete:[{op:'generator',id},{op:'shrine',id:linked.id},{op:'settlement',id:town.id}],fact:'Each marked conductor is connected to the entrance by the baked maze.'});
  content.generators.push({id,structureId:s.id,townId:town.id,puzzleId:p.id,position:positions[2],linkedShrineIds:[linked.id],operationFamily:'balanced',reachableCellCount:cells.length,sourceKind});
  mission('mission:'+id,'The Listening Labyrinth','Meet the three conductors in this labyrinth. First inspect, then match demand 1, 2, 3 and pulse Two → One → Three. Return to the keeper; the linked road shrine will retain the new current.',keeper,[objective('generator','puzzle',[p.id],'Reactivate the maze generator.')],{onComplete:[{op:'text',text:'Proven: the generator and linked shrine answer. Symbol: the chorus calls this reconciliation. Unknown: why the Drift began.'}]});
 }
 // The five authored Kobold hubs regulate their real cave components too.
 for(const town of content.settlements.filter(t=>t.realm==='cave'&&t.settlementTier!=='minor')){
  const p=content.puzzles.find(p=>p.townId===town.id),linked=[...content.shrines].sort((a,b)=>dist(a.position,town.position)-dist(b.position,town.position)||compareId(a.id,b.id))[0],id='generator:'+town.portalId;
  p.onComplete.push({op:'generator',id},{op:'shrine',id:linked.id});
  content.generators.push({id,structureId:town.portalId,townId:town.id,puzzleId:p.id,position:p.position,linkedShrineIds:[linked.id],operationFamily:p.family,sourceKind});
 }
 // Concrete deterministic optional loot; legacy weapons remain evidence, not combat verbs.
 const types=new Map(data.objectInstances.map(i=>[i.typeId,{id:i.typeId,name:i.typeId.replace(/([a-z])([A-Z])/g,'$1 $2'),icon:i.icon,usable:false,note:'Carried evidence; use effects are not implemented.'}]));
 types.set('CopperCoil',{id:'CopperCoil',name:'Salvaged copper coil',usable:false,note:'Optional salvage from the old grid.'});content.itemTypes=[...types.values()];
 for(const c of chunks)for(const o of c.objects)if(o.kind==='chest'){const items=[{id:'item:'+o.id+':0',typeId:'CopperCoil',quantity:1,sourceKind}];content.containers.push({id:o.id,name:'Old grid chest',position:o.position,realm:'surface',items,lock:null,trap:null,sourceKind});anchor('container',o.id,o.position,{prompt:'Open chest'});for(const n of c.nodes)if(n.userData.jcrpg.objectId===o.id)Object.assign(n.userData.jcrpg,{containerId:o.id,interactionId:'interaction:container:'+o.id});}
 // Explicit reconciliation: all fixed ownership survives, even when no house was built.
 const ownership=data.districts.flatMap(d=>d.fixedInfrastructure.map(f=>({districtId:d.id,ownerMemberId:f.ownerMemberId,structureId:structures.find(s=>s.districtId===d.id&&s.ownerMemberId===f.ownerMemberId)?.id??null})));
 for(const record of ownership){record.anchorKind=record.structureId?'owned-structure':'district-fallback';const existing=content.actors.find(a=>a.legacy?.numericId===record.ownerMemberId);if(existing){record.actorId=existing.id;continue;}const legacy=data.actors.find(a=>a.numericId===record.ownerMemberId),town=settlements.get(districtById.get(record.districtId).townId),s=structures.find(s=>s.id===record.structureId);const a=actor(legacy.id,'Resident '+legacy.numericId,'Local witness',town,s?[s.origin[0]-1,s.origin[1],s.origin[2]+1]:town.position,'The Drift changes what reaches our homes. The circuit keepers can explain the regional work; shrines preserve each relay you awaken.',legacy,byCulture[legacy.entityType]);a.anchorKind=record.anchorKind;record.actorId=a.id;}
 for(const list of Object.values(content))if(Array.isArray(list))list.sort((a,b)=>compareId(a.id,b.id));
 for(const s of content.shrines)s.neighbors.sort((a,b)=>compareId(a.id,b.id));
 const maps=validateContent(content);const allAnchors=chunks.flatMap(c=>c.interactions),anchorIds=new Set();for(const a of allAnchors){const group={actor:'actors',shrine:'shrines',puzzle:'puzzles',container:'containers'}[a.kind];if(group&&!maps[group][a.targetId])throw Error('Dangling anchor '+a.id);if(a.kind==='puzzle'&&a.input!=='reset'&&!maps.puzzles[a.targetId].componentIds.includes(a.componentId))throw Error('Unknown puzzle input '+a.id);if(anchorIds.has(a.id))throw Error('Duplicate anchor '+a.id);anchorIds.add(a.id);}
 const navigationReport=validateInteractionNavigation(chunks,content);
 const solvers=content.puzzles.map(p=>({id:p.id,...solvePuzzle(p)}));
 return {content,ownership,report:{navigation:navigationReport,legacyActors:data.actors.length,legacyNPCs:data.actors.filter(a=>!a.isPlayer).length,legacyItems:data.objectInstances.length,fixedOwners:ownership.length,ownerMatches:ownership.filter(o=>o.structureId).length,fallbackAnchors:ownership.filter(o=>!o.structureId).length,actors:content.actors.length,containers:content.containers.length,shrines:content.shrines.length,puzzles:content.puzzles.length,missions:content.missions.length,capitals:6,secondaryCapitals:24,anchors:allAnchors.length,solverWitnesses:solvers.map(s=>({id:s.id,steps:s.inputs.length})),danglingReferences:0,unsolvedPuzzles:0,deviations:['Narrative hierarchy, characters, dialogue, shrine routing, circuit puzzles and concrete loot are authored web content.','Shrine edges are a deterministic proximity graph, not recovered legacy roads.','Actor models are distinct static culture proxies; no MD5 animation runtime.','Regional circuits use accessible settlement controls; labyrinth generators use entrance-connected maze cells.','Surface reachability uses existing collision semantics; terrain slopes and full cross-world route traversal require browser review.']}};
}
