#Game Settings written by org.jcrpg.threed.core.PropertiesGameSettings at Mon Jun 07 22:12:10 CEST 2010
#Mon Jun 07 22:12:10 CEST 2010
SAMPLES=1
FREQ=-1
WIDTH=800
RENDERER=LWJGL
HEIGHT=600
DEPTH=24
FULLSCREEN=false
