RENDER_DISTANCE=80
RENDER_DISTANCE_FARVIEW=40
RENDER_DISTANCE_CALC=40
VIEW_DISTANCE=50
VIEW_DISTANCE_SQR=2500
VIEW_DISTANCE_FRAG_SQR=625
RENDER_GRASS_DISTANCE=20
RENDER_SHADOW_DISTANCE=30
RENDER_SHADOW_DISTANCE_SQR=900
ANTIALIAS_SAMPLES=0
MIPMAP_TREES=true
MIPMAP_GLOBAL=true
TEXTURE_QUALITY=2
SOUND_ENABLED=true
MUSIC_VOLUME_PERCENT=100
EFFECT_VOLUME_PERCENT=60
BLOOM_EFFECT=false
DOF_EFFECT=true
DOF_DETAILED=true
SHADOWS=true
ANIMATED_GRASS=true
DOUBLE_GRASS=false
ANIMATED_TREES=true
DETAILED_TREES=true
DETAILED_TREE_FOLIAGE=true
LOD_VEGETATION=false
WATER_SHADER=true
WATER_DETAILED=false
FARVIEW_ENABLED=false
CONTINUOUS_LOAD=false
DISABLE_DDS=false
LOGGING=true
FPSCOUNTER=false
TEXTURE_SPLATTING=false
SECONDARY_TEXTURES=true
SLOW_ANIMATION=false
VBO_ENABLED=false
NORMALMAP_ENABLED=false
NORMALMAP_DETAILED=false
WITHOUT_COMBATS=false
QUICK_EXIT=false
MOUSELOOK=true
UIMOUSE=true
